from __future__ import annotations

import json
import logging
import os
from datetime import date
from pathlib import Path

import requests

from get_schedule_obj import get_today_schedule
from schedule_obj import ScheduleEntry

CSV_PATH = Path(__file__).parent.parent / "resources" / "schedule_parsed.csv"
JID_MAP_PATH = Path(__file__).parent.parent / "resources" / "jid_map.json"

EVOLUTION_API_URL = "http://evolution-api:8081/message/sendText/0123226431"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
log = logging.getLogger(__name__)


def format_message(entry: ScheduleEntry) -> str:
    lines = [
        f"*Class Reminder* ({entry.week})",
        f"Date: {entry.date} ({entry.day})",
        f"Time: {entry.time}",
        f"Venue: {entry.venue}",
        f"Lecturer: {entry.lecturer}",
        f"*This message generated by a bot*"
    ]
    return "\n".join(lines)


def send_whatsapp_message(jid: str, text: str, api_key: str) -> None:
    payload = {"number": jid, "text": text}
    headers = {
        "apikey": api_key,
        "Content-Type": "application/json",
    }
    response = requests.post(
        EVOLUTION_API_URL, json=payload, headers=headers, timeout=15
    )
    response.raise_for_status()
    log.info("Message sent to %s (HTTP %s)", jid, response.status_code)


def main() -> None:
    api_key = os.getenv("EVOLUTION_API_KEY") or os.getenv("AUTHENTICATION_API_KEY", "")
    if not api_key:
        log.error(
            "Missing required environment variable: EVOLUTION_API_KEY or AUTHENTICATION_API_KEY"
        )
        raise SystemExit(1)

    today = date.today()
    entries = get_today_schedule(str(CSV_PATH))
    log.info("Schedule for %s: %d entries", today, len(entries))

    if not entries:
        log.info("No classes today, nothing to send.")
        return

    with JID_MAP_PATH.open() as f:
        jid_map: dict[str, str] = json.load(f)

    for entry in entries:
        jid = jid_map.get(entry.lecturer, "")
        if not jid:
            log.warning("No JID configured for lecturer: %s — skipping", entry.lecturer)
            continue
        message = format_message(entry)
        log.info("Sending reminder to %s for lecturer %s", jid, entry.lecturer)
        send_whatsapp_message(jid, message, api_key)


if __name__ == "__main__":
    main()
